### ISSUE TITLE
Healthbar frame and bar height mismatch.

### ISSUE THREAD

**Issue by PlasmaPunch** [Ascension-Addons/ElvUI#42]
### Description

My Healthbar size doesn't take up the full height I have it set to. It's set to 40, with a 40 size button for reference. in the picture. I have tried disabling the powerbar, etc and otherwise I have no idea why it's doing this.

I assume it's the empty space is the Powerbar space, but if I make the size 60, with Powerbar 20 it still doesn't make it size 40, for example. However even with the powerbar attached the frame size is mismatched from bar size so the glows are really weird.

![image](https://github.com/Ascension-Addons/ElvUI/assets/38546519/8cc1b0e3-cfe7-43db-bdba-3b18cfc3d2ef)
![image](https://github.com/Ascension-Addons/ElvUI/assets/38546519/6691bd72-ea44-499a-a3c0-2556f28e27cc)
![image](https://github.com/Ascension-Addons/ElvUI/assets/38546519/e41e7402-4ab2-499e-aa5b-18972213c8be)
![image](https://github.com/Ascension-Addons/ElvUI/assets/38546519/9c50744d-93ed-4785-a14e-8bf1c3f45f9e)

Below are for the non-ascension version of ElvUI. on another 3.3.5 server:
![image](https://github.com/Ascension-Addons/ElvUI/assets/38546519/1bf7aeac-9952-4e19-9178-fdf3e34c4f53)
![image](https://github.com/Ascension-Addons/ElvUI/assets/38546519/d5a06a23-4b92-473f-bef9-5b84d26d7eb9)

### Realm

Rexxar

### Tested with only this addon

- [X] Yes
- [ ] No

### Reproduction Steps

1. Customize Unitframes > Player
2. Change Height in the General Tab
3. Observe mismatch is Healthbar Height and frame height.

**Comment by andrew6180** [comment]
Resolved with 7.3
