### ISSUE TITLE
[CoA] Starcaller Energy Bar always-on and attached to Health Bar

### ISSUE THREAD

**Issue by PlasmaPunch** [Ascension-Addons/ElvUI#43]
### Description

Starcaller uses Energy and Mana, your Energy is always attached to Player UF even if Power is disabled.

Enabled:
![image](https://github.com/Ascension-Addons/ElvUI/assets/38546519/7823b01d-af44-4c59-abf7-97dd09980288)

Disabled:
![image](https://github.com/Ascension-Addons/ElvUI/assets/38546519/3c43210e-0194-4a77-8d9c-a945c655a515)

### Realm

Rexxar

### Tested with only this addon

- [X] Yes
- [ ] No

### Reproduction Steps

Make a Starcaller
Look at Unitframes
Disable/Enable Power

**Comment by andrew6180** [comment]
It's under `Classbar`
