### ISSUE TITLE
Latest update broke stance bars

### ISSUE THREAD

**Issue by Blinkyqt** [Ascension-Addons/ElvUI#44]
### Description

https://github.com/Ascension-Addons/ElvUI/pull/40

This update broke stance bar for Def stance/bear form 

### Realm

Area 52 (Default)

### Tested with only this addon

- [X] Yes
- [ ] No

### Reproduction Steps

Use bear form
cant cast spells

**Comment by mattcapazz** [comment]
#40 nor #41 had any changes made to HERO class. Are you sure you're referring to A52?

**Comment by mattcapazz** [comment]
#40 nor #41 had any changes made to the `HERO` class. Are you sure you're referring to `Area 52`?
I just tested it in both `Archimonde` & `Area 52`, and for me in both realms it changes the bars as expected.
![_output](https://github.com/Ascension-Addons/ElvUI/assets/38044816/f4ed8990-b230-4913-aa8a-9412f27fcf47)

**Comment by BanditTech** [comment]
I was under the impression that stealth is a stance of its own, and you cannot be in bear form and stealth at the same time

**Comment by BanditTech** [comment]
I think this change might have been made on the backend, since there are bear builds which have issues with spells removing the stance. I noticed that my corrupted bear form is able to spam Shadow Bolt while stationary and it does not drop you from your shapeshift.

**Comment by andrew6180** [comment]
Likely needs a bug report if still an issue. Elvui has no changed. If still having issues, confirm normal action bars aren't also broken.
