### ISSUE TITLE
ElvUI_AscensionExtendedUI.lua spams LUA errors

### ISSUE THREAD

**Issue by Zojak123** [Ascension-Addons/ElvUI#48]
### Description

The latest version seems to be spamming LUA errors when loaded

### Realm

Seasonal

### Tested with only this addon

- [X] Yes
- [ ] No

### Lua Error

Date: 2023-12-19 11:13:36
ID: 2
Error occured in: Global
Count: ∞
Message: ...UI_AscensionExtendedUI\ElvUI_AscensionExtendedUI.lua line 36:
   attempt to index field 'backdrop' (a nil value)
Debug:
   [C]: ?
   ...UI_AscensionExtendedUI\ElvUI_AscensionExtendedUI.lua:36: AscensionUIExtended()
   ...UI_AscensionExtendedUI\ElvUI_AscensionExtendedUI.lua:16: onUpdate()
   ...UI_AscensionExtendedUI\ElvUI_AscensionExtendedUI.lua:7:
      ...UI_AscensionExtendedUI\ElvUI_AscensionExtendedUI.lua:7
AddOns:
  Swatter, v5.9.4960 (WhackyWallaby)
  AscensionClassTalent, v1.0.0
  AscensionCollections, v1.0.0
  AscensionSkillCards, v1.0.0
  AscensionWildCard, v1.0.0
  AscensionUI, v
  ElvUI, v7.8
  ElvUIAddOnSkins, v1.06
  ElvUIAscensionExtendedUI, v
  ElvUIEnhanced, v1.05
  ElvUIEnhancedFriendsList, v1.09
  ElvUIExtraActionBars, v1.00
  BlizRuntimeLib_enUS v3.3.5.30300 <162.19.28.88>
  (ck=17c)

### Reproduction Steps

There is no specific steps to reproduce. Got the error Messages after login

### Screenshots

![grafik](https://github.com/Ascension-Addons/ElvUI/assets/154324165/3fc9226c-7b38-4b1b-9800-e4b066e956a0)

**Comment by andrew6180** [comment]
ElvUI_AscensionExtendedUI is not part of the launcher version. Delete it and use the version from the launcher.
