### ISSUE TITLE
ElvUI Enhanced - Equipment Info not displaying Item level of equipped gear

### ISSUE THREAD

**Issue by bedle** [Ascension-Addons/ElvUI#51]
### Description

ElvUI Config - Enhanced - Equipment Info

Item Level (Toggled on):

What it should do:
It should show Item Level of equipped items on Character frame.

What it does:
It does not show item level of equipped items

How to replicate:
Just toggle on "Item Level" like in attached image.
![Item Level](https://github.com/Ascension-Addons/ElvUI/assets/62448955/3c42c088-a6b2-4ac1-94b7-c2b61fdc1880)

### Realm

Seasonal

### Tested with only this addon

- [X] Yes
- [ ] No

### Lua Error

No lua Errors

### Reproduction Steps

1. ElvUI
2. Enhanced
3. Equipment Info
4. Toggle on "Item Level"

### Last Good Version

//

### Screenshots

![Item Level](https://github.com/Ascension-Addons/ElvUI/assets/62448955/e53b76f2-2013-4b03-9dea-cf5ca99ee528)

**Comment by Juggalo187** [comment]
Yeah and even if you disable all addons and try using addons made just to add ilvl to the icons they also won't work. I think it has something to do with changes they made to the client files.

**Comment by andrew6180** [comment]
fixed in https://github.com/Ascension-Addons/ElvUI/commit/450fc5f9ef78bda6122f786f48b8133c56ac389d
