### ISSUE TITLE
Massive lagspikes on Hallow's End with Chat enabled

### ISSUE THREAD

**Issue by Zeffuro** [Ascension-Addons/ElvUI#54]
### Description

Getting massive lag spikes every so often when walking around doing questing. Turning the ElvUI chat module off fixes the issue.

### Realm

Other

### Tested with only this addon

- [X] Yes
- [ ] No

### Lua Error

3x ElvUI-7.17\Modules\Chat\Chat.lua:1098: bad argument #1 to 'format' (string expected, got nil)
ElvUI-7.17\Modules\Chat\Chat.lua:1098: in function `ChatFrame_MessageEventHandler'
ElvUI-7.17\Modules\Chat\Chat.lua:1242: in function `ChatFrame_OnEvent'
ElvUI-7.17\Modules\Chat\Chat.lua:1246: in function `FloatingChatFrame_OnEvent'
ElvUI-7.17\Modules\Chat\Chat.lua:1251: in function <ElvUI\Modules\Chat\Chat.lua:1250>

Locals:
self = <table> {
 OnEnter = <function> @ ElvUI\Modules\Chat\Chat.lua:530:
 PositionChat = <function> defined =[C]:-1
 OnHyperlinkLeave = <function> @ ElvUI\Modules\Chat\Chat.lua:865:
 UpdateChatTabColors = <function> @ ElvUI\Modules\Chat\Chat.lua:748:
 EnableModule = <function> @ Interface\LibraryXML\AceAddon-3.0\AceAddon-3.0.lua:363:
 modules = <table> {}
 CancelTimer = <function> @ Interface\LibraryXML\AceTimer-3.0\AceTimer-3.0.lua:166:
 IterateEmbeds = <function> @ Interface\LibraryXML\AceAddon-3.0\AceAddon-3.0.lua:473:
 SecureHookScript = <function> @ Interface\LibraryXML\AceHook-3.0\AceHook-3.0.lua:410:
 DisplayChatHistory = <function> @ ElvUI\Modules\Chat\Chat.lua:1569:
 DisableChatThrottle = <function> @ ElvUI\Modules\Chat\Chat.lua:895:
 ON_FCF_SavePositionAndDimensions = <function> @ ElvUI\Modules\Chat\Chat.lua:1665:
 RawHookScript = <function> @ Interface\LibraryXML\AceHook-3.0\AceHook-3.0.lua:395:
 baseName = "ElvUI"
 AddLines = <function> @ ElvUI\Modules\Chat\Chat.lua:1468:
 HandleShortChannels = <function> @ ElvUI\Modules\Chat\Chat.lua:903:
 Keywords = <table> {}
 SetDefaultModulePrototype = <function> @ Interface\LibraryXML\AceAddon-3.0\AceAddon-3.0.lua:440:
 CHAT_MSG_YELL = <function> @ ElvUI\Modules\Chat\Chat.lua:1384:
 db = <table> {}
 defaultModuleState = true
 ChatFrame_SystemEventHandler = <function> @ ElvUI\Modules\Chat\Chat.lua:1235:
 IsEnabled = <function> @ Interface\LibraryXML\AceAddon-3.0\AceAddon-3.0.lua:482:
 RefreshToggleButtons = <function> @ ElvUI\Modules\Chat\Chat.lua:639:
 ScheduleTimer = <function> @ Interface\LibraryXML\AceTimer-3.0\AceTimer-3.0.lua:113:
 DisableModule = <function> @ Interface\LibraryXML\AceAddon-3.0\AceAddon-3.0.lua:381:
 HookSecured = true
 OnLeave = <function> @ ElvUI\Modules\Chat\Chat.lua:538:
 ResetHistory = <function> @ ElvUI\Modules\Chat\Chat.lua:1970:
 ResetEditboxHistory = <function> @ ElvUI\Modules\Chat\Chat.lua:1966:
 RegisterMessage = <function> @ Interface\LibraryXML\CallbackHandler-1.0\CallbackHandler-1.0.lua:116:
 UnregisterMessage = <function> @ Interface\LibraryXML\CallbackHandler-1.0\CallbackHandler-1.0.lua:179:
 UpdateSettings = <function> @ ElvUI\Modules\Chat\Chat.lua:444:
 SetupChat = <function> @ ElvUI\Modules\Chat\Chat.lua:1267:
 hooks = <table> {}
 GetPlayerInfoByGUID = <function> @ ElvUI\Modules\Chat\Chat.lua:1928:
 ChatThrottleIntervalHandler = <function> @ ElvUI\Modules\Chat\Chat.lua:1366:
 UpdateChatTabs = <function> @ ElvUI\Modules\Chat\Chat.lua:611:
 DefaultSmileys = <function> @ ElvUI\Modules\Chat\Chat.lua:1699:
 TabStyles = <table> {}
 BuildCopyChatFrame = <function> @ ElvUI\Modules\Chat\Chat.lua:1800:
 FCF_SetWindowAlpha = <function> @ ElvUI\Modules\Chat\Chat.lua:1661:
 SetEnabledState = <function> @ Interface\LibraryXML\AceAddon-3.0\AceAddon-3.0.lua:455:
 Hook = <function> @ Interface\LibraryXML\AceHook-3.0\AceHook-3.0.lua:274:
 enabledState = true
 SaveChatHistory = <function> @ ElvUI\Modules\Chat\Chat.lua:1629:
 RegisterEvent = <function> @ Interface\LibraryXML\CallbackHandler-1.0\CallbackHandler-1.0.lua:116:
 DelayGuildMOTD = <function> @ ElvUI\Modules\Chat\Chat.lua:1589:
 UpdateFading = <function> @ ElvUI\Modules\Chat\Chat.lua:1561:
 ChatThrottleBlockFlag = <function> @ ElvUI\Modules\Chat\Chat.lua:1348:
 UpdateChatKeywords = <function> @ ElvUI\Modules\Chat\Chat.lua:1548:
 IterateModules = <function> defined @Interface\LibraryXML\Ac
  ---

### Reproduction Steps

1. Have ElvUI 7.17.
2. Play on Hallow's End Realm (might occur on Rexxar too, not sure).
3. Get minifreezes/lagspikes every 5 seconds or so while walking.
4. I seem to get it more frequently when entering a new zone.

### Last Good Version

Was working fine on the other realms

### Screenshots

https://github.com/user-attachments/assets/07c35eda-90e5-4a91-8759-8c808bfc6c3d

Video of this occurring

**Comment by Zeffuro** [comment]
I think https://github.com/Ascension-Addons/ElvUI/commit/6d74de6c27a97efc993ac427a93603414bf941cc fixed the issue but I'll keep an eye on it to see if it stays good.

**Comment by andrew6180** [comment]
fixed with https://github.com/Ascension-Addons/ElvUI/commit/6d74de6c27a97efc993ac427a93603414bf941cc
